### ISSUE TITLE
API: popular groups endpoint does not exist

### ISSUE THREAD

**Issue by ohienko1991** [PowerlineApp/powerline-server#127]
https://api-dev.powerli.ne/api/groups/popular 
I think this api call doesn't exist in current backend, it must be worked same as previous backend version.

**Comment by austinpapp** [comment]
looks like the `@Route` is the wrong endpoint. See https://github.com/PowerlineApp/powerline-server/blob/develop/backend/src/Civix/ApiBundle/Controller/GroupController.php#L337-L387

line 384 needs to be: 
`@Route("/popular", name="civix_api_groups_popular_groups")`
