### ISSUE TITLE
Enhance Saved item endpoint

### ISSUE THREAD

**Issue by habibillah** [PowerlineApp/powerline-server#187]
Enhance Favorites/Saved Items endpoint a bit more so that it can work with all types and so that it can return more of the details of the items (we want the Favorites list in the app to show each item as if it were the newsfeed)

@jterps08, do you know the list of **all types** as mentioned above? and also the **additional details** data need to be added to the existing one?

**Comment by austinpapp** [comment]
@habibillah take a look here https://github.com/PowerlineApp/powerline-mobile/issues/37#issuecomment-230341219

**Comment by austinpapp** [comment]
i think we've already covered most of the types of content we want to favorite. however we need to expand on the attributes about the favorites. per powerline-mobile#37 

* title
* description
* author
* group_id
* created_at

**Comment by habibillah** [comment]
@jterps08 since the saved item save various type of entities, I decide to show the schema based on their original entity. For example saved item for `petition` will show the schema same as [`GET /api-public/petition/{id}`](https://api-dev.powerli.ne/api-doc#get--api-public-petition-{id}) response.

The details of each items in saved item stored on `detail` fields. See image below.

![sc_b777](https://cloud.githubusercontent.com/assets/547094/16975905/0b78cd26-4e75-11e6-9226-cc79309edf19.png)

The complete sample of the response can be found at https://gist.github.com/habibillah/7cde307f64573837d7a13c4ac75648b3

If that still doesn't make sense, I can construct each item into below format:

````
[{
  "id": "",
  "title": "",
  "description": "",
  "author": "",
  "created_at": "",
  "group_id": ""
}]
````

But please help me by let me the appropriate field in each entity to fit the above schema. For example: `petition` entity have `petition_body` that easily can be converted into `description`. But `petition_answer` entity doesn't have `title` and `description`. The `post` entity doesn't have `author` field.

Currently, saved item support for:

- petition
- petition_comment
- petition_answer
- poll
- poll_comment
- poll_answer
- post

Let see your comments

**Comment by jterps08** [comment]
Thanks Habibillah - I need to bring in @austinpapp for this

**Comment by austinpapp** [comment]
this was deployed

**Comment by habibillah** [comment]
Thank you @austinpapp for the deployment. let see @petervojtek comment on this issue, since I believe it related to [his work](https://github.com/PowerlineApp/powerline-mobile/issues/37#issuecomment-230231082).

**Comment by petervojtek** [comment]
I don't know the whole context, but from mobile app point of view it would be best if the Favorites resource would contain exactly the same fields as Newsfeed Activity resource, because we [want to render them the same way](https://github.com/PowerlineApp/powerline-mobile/issues/37#issuecomment-230375910).

Currently they seem to differ quite a lot:

Here is an activity item:
```
{"id":444,"title":"Provide free bowling ..","description":"test.","sent_at":"Tue, 19 Jul 2016 04:50:24 +0000","expire_at":"Wed, 20 Jul 2016 04:50:24 +0000","responses_count":0,"owner":{"id":71,"type":"user","official_title":"","first_name":"Peter9","last_name":"Peter9","avatar_file_path":"https://api-dev.powerli.ne/bundles/civixfront/img/default_user.png"},"entity":{"type":"micro-petition:long-petition","id":217,"group_id":282},"picture":null,"read":true,"rate_up":null,"rate_down":null,"image_src":null,"updated_at":"2016-07-19T04:50:24+0000","metadata":null,"quorum":0}
```

And here is how the item is provided as Favorite:
```
{"id":30,"item_id":217,"type":"petition","detail":{"quorum_count":0,"id":217,"title":"Provide free bowling ..","petition_body":"test.","group":{"id":282,"type":"group","group_type":3,"avatar_file_path":"https://api-dev.powerli.ne/bundles/civixfront/img/default_group.png","official_title":"Fresno","group":{"id":6,"type":"group","group_type":2,"avatar_file_path":"https://api-dev.powerli.ne/bundles/civixfront/img/default_group.png","official_title":"California","acronym":"CA","group":{"id":1,"type":"group","group_type":1,"avatar_file_path":"https://api-dev.powerli.ne/bundles/civixfront/img/default_group.png","official_title":"The United States of America","acronym":"US"}}},"group_id":282,"created_at":"Tue, 19 Jul 2016 04:50:24 +0000","expire_at":"Wed, 20 Jul 2016 04:50:24 +0000","user":{"full_name":"Peter9 Peter9","id":71,"type":"user","username":"Peter9","first_name":"Peter9","last_name":"Peter9","zip":"111","avatar_file_name":"https://api-dev.powerli.ne/bundles/civixfront/img/default_user.png","birth":"01/01/1977","address1":"Fresno","city":"Fresno","state":"CA","country":"US","interests":[]},"publish_status":0,"type":"long petition","options":[{"id":1,"value":"Upvote","votes_count":0},{"id":2,"value":"Downvote","votes_count":0}],"cached_hash_tags":[],"responses_count":0},"created_at":"Fri, 22 Jul 2016 05:50:11 +0000"}
```

And as you can see, the activity has `entity.type=micro-petition:long-petition`, while its favorite representation has `type=petition`.

**Comment by habibillah** [comment]
I think you need to go to `"detail": {}` field.

what endpoint you use to get this response?
`````
{"id":444,"title":"Provide free bowling ..","description":"test.","sent_ ... ....
`````

**Comment by petervojtek** [comment]
I use `GET /api/v2/activities` to fetch activities and `GET /api/bookmarks/list/all` for favorites.

**Comment by habibillah** [comment]
@austinpapp, @jterps08, do you aware there are similar entities? do you plan to remove the older and replaced with newer one? or both old and new still used together? Can someone tell me what the differences? when will I use the older, and when need to user the newest entities?

````
// new entity in version 2
Civix\CoreBundle\Entity\Activities\Question
Civix\CoreBundle\Entity\Activities\Petition
Civix\CoreBundle\Entity\Activities\MicroPetition

// The older entity
Civix\CoreBundle\Entity\Poll\Question
Civix\CoreBundle\Entity\Micropetitions\Petition
````

**Comment by jterps08** [comment]
@habibillah - I think that @austinpapp needs to answer this question. The new entities were created by Angel a few months ago. I'm pretty sure we want to be using those new entities, but I need Austin to confirm on your question and the discussion above.

**Comment by austinpapp** [comment]
@habibillah it would seem everything listed here: https://github.com/PowerlineApp/powerline-server/blob/develop/backend/src/Civix/CoreBundle/Entity/Activity.php

**Comment by habibillah** [comment]
@austinpapp, classes below is not use any more?

````
// The older entity
Civix\CoreBundle\Entity\Poll\Question
Civix\CoreBundle\Entity\Micropetitions\Petition
````

**Comment by austinpapp** [comment]
I'm not positive they aren't used any more. We will need to touch base with Igor. However, whatever the activities controller is using, those are the entities we are targeting

**Comment by habibillah** [comment]
OK, I just switch saved item to use newest entity. So it now just support for 
- petition
- micro petition
- question

The complete response sample can be found at [here](https://gist.github.com/habibillah/40ca4eb9300eb972b4c601a5a184fe65)

@petervojtek, the saved item response now have similar schema as activity schema. Just look at `detail` field.

**Comment by jterps08** [comment]
Given the way `question` is used now, I believe that will allow us to save any poll, petition, discussion, fundraiser, or event from a leader... 
@austinpapp This is another one of those things that would be impacted by a the terminology initiative.

**Comment by austinpapp** [comment]
@jterps08 yes it would. be again, this is not as simple as renaming a class...

**Comment by habibillah** [comment]
now it support all `Activity subclass`.

- petition
- micro_petition
- question
- leader_news
- payment_request
- crowdfunding_payment_request
- leader_event

> I believe that will allow us to save any poll, petition, discussion, fundraiser, or event from a leader... 

@jterps08 @austinpapp, can you let me know the class entity that used by the items that mentioned by @jterps08 above?

**Comment by austinpapp** [comment]
https://github.com/PowerlineApp/powerline-server/issues/209 was deployed.

**Comment by jterps08** [comment]
@habibillah - I'm pretty sure the class entity is 'question' but I will need austin to confirm.

J

**Comment by habibillah** [comment]
Did you mean that poll, petition, discussion, fundraiser, and event are stored as Question entity class?

**Comment by jterps08** [comment]
I believe so. I just need Austin to confirm. 

Here's the rationale:
https://github.com/PowerlineApp/powerline-server/wiki/Question
https://github.com/PowerlineApp/powerline-server/wiki/Petition "Use question to receive data"
https://github.com/PowerlineApp/powerline-server/wiki/Event "Use question to receive data"
https://github.com/PowerlineApp/powerline-server/wiki/Payment-Request "Use question to receive data"
https://github.com/PowerlineApp/powerline-server/wiki/Discussion "Use question to receive data"

**Comment by habibillah** [comment]
@jterps08 it now in dev server and will fit your requirment

**Comment by petervojtek** [comment]
@habibillah , I experience following behaviour:

as user Peter12 (id=75) I bookmarked this micro-petition:quorum

Request URL:https://api-dev.powerli.ne/api/bookmarks/add/micro_petition/220
Request Method:POST
Status Code:200 OK

response:
{"id":32,"item_id":220,"type":"micro_petition","created_at":"Sun, 24 Jul 2016 11:36:13 +0000"}

This is the bookmarked micro-petition activity item and as you can see, I fetched the ID=220 from entity.id:

```
{"id":447,"title":"","description":"give us more #pokemons","sent_at":"Fri, 22 Jul 2016 09:04:13 +0000","expire_at":"Sat, 23 Jul 2016 09:04:12 +0000","responses_count":0,"owner":{"id":73,"type":"user","official_title":"","first_name":"Peter10","last_name":"Peter10","avatar_file_path":"http:\/\/devpowerline.s3-website-eu-west-1.amazonaws.com\/avatars\/577cb68e6f276.jpeg"},"entity":{"type":"micro-petition:quorum","id":220,"group_id":285},"picture":null,"read":true,"rate_up":null,"rate_down":null,"image_src":null,"updated_at":"2016-07-22T09:04:13+0000","metadata":null,"quorum":1}
```

When I then fetch list of bookmarks, it seems I see some completely different bookmarks, though the ID=220 is there:

```
Request URL:https://api-dev.powerli.ne/api/bookmarks/list/all/1
Request Method:GET
Status Code:200 OK

{"page":"1","total_pages":1,"total_items":"2","items":[{"id":32,"item_id":220,"type":"micro_petition","detail":{"id":220,"title":"","description":"hi..!!! :)","sent_at":"Thu, 03 Sep 2015 11:59:11 +0000","expire_at":"Fri, 04 Sep 2015 11:59:11 +0000","responses_count":0,"owner":{"id":44,"type":"user","official_title":"","first_name":"Anush","last_name":"Osp","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},"entity":{"type":"micro-petition:quorum","id":74,"group_id":77},"read":false,"updated_at":"-0001-11-30T00:00:00+0000","metadata":{},"quorum":0},"created_at":"Sun, 24 Jul 2016 11:36:13 +0000"},{"id":31,"item_id":222,"type":"micro_petition","detail":{"id":222,"title":"test","description":"test petititon","sent_at":"Thu, 03 Sep 2015 12:07:27 +0000","expire_at":"Fri, 04 Sep 2015 12:07:27 +0000","responses_count":0,"owner":{"id":44,"type":"user","official_title":"","first_name":"Anush","last_name":"Osp","avatar_file_path":"https:\/\/api-dev.powerli.ne\/bundles\/civixfront\/img\/default_user.png"},"entity":{"type":"micro-petition:long-petition","id":76,"group_id":77},"read":false,"updated_at":"-0001-11-30T00:00:00+0000","metadata":{},"quorum":0},"created_at":"Sun, 24 Jul 2016 11:34:00 +0000"}]}
```

There seems to be some ID mismatch -- not sure if it is me who is using wrong ID to store a bookmark.

**Comment by habibillah** [comment]
As I see on your comment above, you bookmark an `id = 220` by call `/api/bookmarks/add/micro_petition/220`. When you call `/api/bookmarks/list/all/1` it return all list including entity with `id = 220`

If you expect to fetch `{"id":447,"title":"","descripti ... ...`, you need to bookmark `id = 447` instead of `220`

**Comment by petervojtek** [comment]
@habibillah , thanks - I confirm I am able to create a bookmark using `activity.attributes.id`.

However, which ID am I supposed to use to [delete a bookmark](https://api-dev.powerli.ne/api-doc#delete--api-bookmarks-remove-{id})?

Here is my bookmarked item (obtained via):

```
{"id":452,"title":"","description":"Free beer for everyone","sent_at":"Sun, 24 Jul 2016 12:18:14 +0000","expire_at":"Mon, 25 Jul 2016 12:17:56 +0000","responses_count":0,"owner":{"id":75,"type":"user","official_title":"","first_name":"Peter12","last_name":"Peter12","avatar_file_path":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/577df93a7df44.jpeg"},"entity":{"type":"micro-petition:quorum","id":223,"group_id":289},"read":false,"updated_at":"2016-07-24T12:18:14+0000","quorum":0}
```

When I try to use id=452 (`bookmark.id`), I receive:

```
Request URL:https://api-dev.powerli.ne/api/bookmarks/remove/452
Request Method:DELETE
Status Code:404 Not Found
```

And the same behaviour is for the other ID=223 (`bookmark.entity.id`):

```
Request URL:https://api-dev.powerli.ne/api/bookmarks/remove/223
Request Method:DELETE
Status Code:404 Not Found
```

**Comment by habibillah** [comment]
To delete bookmark, you need to use the bookmark ID. Let see the response from `GET /api/bookmarks/list/all/` below

````
{"page":"1","total_pages":1,"total_items":"2","items":[{"id":32,"item_id":220, .... ...
````
To remove the bookmark, you need to use `id` attribute in `items` collection, which is `32`.

**Comment by petervojtek** [comment]
thank you @habibillah  , I overlooked it.

**Comment by habibillah** [comment]
@petervojtek, I will let you know that PR #215 will contain changes on bookmark types. See api doc for more detail.

| before                                          |  After                                             |
|-------------------------------------------|-------------------------------------------|
|petition                                          | petition                                          |
micro_petition                                | micro-petition                                 |
question | question
leader_news | leader-news
payment_request | payment-request
crowdfunding_payment_request |     crowdfunding-payment-request
leader_event |  leader-event

This change to make more consistent between activity type and bookmark type.
