### ISSUE TITLE
Can't run migration

### ISSUE THREAD

**Issue by habibillah** [PowerlineApp/powerline-server#191]
See image below for the error message

![sc_7a7c](https://cloud.githubusercontent.com/assets/547094/16892578/611e129a-4b41-11e6-938d-13edc84ba515.png)

**Comment by jterps08** [comment]
@igaponov Can you take a look at this? I'm not sure if this is you or @austinpapp 

@habibillah - Just so you know, we are using the "Assignees" feature actively now in GitHub. If you run into other server issues, please assign to Austin. When complete, please assign to Austin. He will work on it or re-assign to Igor as needed. Thanks!

**Comment by igaponov** [comment]
@habibillah try to clear cache. There is no mention of AnnouncementPushSenderListener in develop branch now.

**Comment by jterps08** [comment]
@habibillah let us know if Igor's comment helps
