### ISSUE TITLE
Open discussion up for reivew of leader content

### ISSUE THREAD

**Issue by austinpapp** [PowerlineApp/powerline-server#202]
Let's start chatting about how we make leader content easier to understand and develop against. This *does not* mean we are working on this immediately as this work would require some significant work (refactoring). However, I would like to start documenting it here.  

## Leader Overview for Content Types

Part of the leader experience is to create various engagement entities such as a fundraisers or classic polls. This is meant to employ constituents or members to take action in some way. 
 
### Leader content types:
* Poll
* Fundraiser
* Discussion
* Event
* Petition

The types themselves i think are pretty explanatory and are handle exactly like you'd expect a poll to be conducted, or a petition to be signed. 

## Developer Overview

Creating any one of these leader types is trivial but not obvious. 

The current process utilizes the group's `poll` endpoint. In order to distinguish between content types, specific combinations of parameters will define what type you are attempting to create. 

As an example, to create an `event`, we call `/api/v2/groups/{group}/polls` passing the following parameters
```python
{
    "type"          : "event",
    "subject"       : "event subject",
    "title"         : "the event title for something cool",
    "started_at"    : "2016-07-20T08:26:14.579185",
    "finished_at"   : "2016-08-20T08:26:14.579185"
}
```

You can view the current implementation here: [api-dev.powerli.ne/api-doc](https://52.5.45.80/api-doc#post--api-v2-groups-{group}-polls)

### Endpoints

* Each leader content type must have it's own endpoint
* Each endpoint must consider all HTTP verbs as appropriate

#### Events Example

Endpoint:
`/api/v2/groups/{group}/events`

Parameters:
_Not limited to the following parameters as they meet the current implementation_
```json
{
    "subject"       : "event subject",
    "title"         : "the event title for something cool",
    "started_at"    : "2016-07-20T08:26:14.579185",
    "finished_at"   : "2016-08-20T08:26:14.579185"
}
```

### Backend

Originally all content types were based from a `Question`. However, I'm not 100% clear on if we actually inherit anything from a `question` class. I'm also not sure how useful this is here. Most of this types do in fact have commonalities across them which we need to explore in greater detail. I'm purposely leaving this open-ended as only upon further investigation can we really figure how to best handle this in the backend. The does go without saying that OOD should be considered best path forward. 

Also, I assume once we have identified the proper classes we should be able to easily persist this data appropriate in the database. I'm simply guessing that each entity will be it's own table. However, we will chat more about that.

**Comment by jterps08** [comment]
I think we have addressed this as best as we can for now. Closing.
