### ISSUE TITLE
Review purpose of username for group creation

### ISSUE THREAD

**Issue by austinpapp** [PowerlineApp/powerline-server#207]
We need to understand if we can remove the username requirement for creating a group. If i want to create 2 groups, i must have a unique username for each group i create. the group name (`official_name`)  isn't what is unique. i've created 3 of the same groups with different usernames. this seems wrong to me. 

fwiw, i've already logged in and therefore we should be able to easily track a user who is creating a group.

**Comment by austinpapp** [comment]
@igaponov do you have any thoughts on this?

**Comment by igaponov** [comment]
@austinpapp we can delete group's username, but have to delete all related code (group's registration, authorization etc) and it's not fast.

**Comment by jterps08** [comment]
@austinpapp @igaponov I recommend thinking about this in the same way that Twitter or Facebook or even GitHub think about it... Ask for the group name and auto-create the username, but allow the user to change the username (or group name) later. The groupname is the field that will be used from a URL routing standpoint anyway. This seems to me to be the easiest path - just have the group username itself auto-defined by the system (combine, truncate, add number, something SaveTheWhales3) and we can create a way to update it later. Thoughts?

**Comment by jterps08** [comment]
@igaponov @austinpapp whats's our status with this? I have a feeling we need to have an answer to this in order to test new group registration flow (with subscriptions)

**Comment by igaponov** [comment]
@jterps08 we need group's username only for registration/login. If we don't need this feature now, we can delete it (with a password, token, etc), but have to delete all related code also (registration/login for groups). Probably can do it after next release to prod?

**Comment by jterps08** [comment]
After next release sounds good. Labeling this refactoring. Thanks Igor.

**Comment by jterps08** [comment]
Closing due to #364
