### ISSUE TITLE
Group creation generates a 500

### ISSUE THREAD

**Issue by austinpapp** [PowerlineApp/powerline-server#208]
Created a group as such:
```python
new_group = {
    'username'          : 'austin1',
    'official_type'     : 'Business',
    'official_name'     : 'another cool busines group'
    }
```
this returned:
```
<Response [500]>
{"code":500,"message":"The parameters passed to the API were invalid. Check your inputs!","errors":null}
```

the group table is in fact populated with the entry and i can return info on that group (id=308)
```python
{u'total_members': 0, u'official_description': None, u'permissions_changed_at': None, u'official_city': None, u'required_permissions': [], u'joined': 0, u'official_address': None, u'fill_fields_required': False, u'acronym': None, u'official_title': u'another cool busines group', u'official_state': None, u'group_type': 0, u'membership_control': u'public', u'manager_phone': None, u'id': 308, u'avatar_file_path': u'https://api-dev.powerli.ne/bundles/civixfront/img/default_group.png'}
```

**Comment by jterps08** [comment]
A few thoughts here:
1) The creator of the group should be automatically joined to the group (group creators are also group members)
2) I am still unclear as to whether we actually need username field or not.

**Comment by austinpapp** [comment]
@jterps08 `username` was what we needed to manage the account. so as expected, we needed to log into the admin portal as that user (there is also a `password` and `salt` column in the group table) to create petitions, polls, etc. Since we now have SSO (so to speak), we are now tying the user account to the group owner. This _should_ eliminate `username` et al. 

The problem we currently are facing is anyone who created a group and managed it the old way, currently have no way of managing the group (UI and API in progress). There is no longer a log in admin portal to do this. The good news is that `group.user_id` references the proper user who created the group so we have that. 

While we review/sort that out, it maybe useful to release the unique index on `username` and make it nullable for now. this gets us away from having to have unique usernames for each group (or even supply it!) when in fact it should be the `official_name` that has the unique constraint.

**Comment by jterps08** [comment]
Just to be clear, we do not need to make this backward compatible with old system as far as old groups being able to log in with new system... In fact, if we need a solution, a command to assign me as group owner of all previous groups is acceptable, and I can assign manager privileges as needed. 

I leave it to you and Igor to discuss the solution you propose above.
