### ISSUE TITLE
Tear down beta endpoint

### ISSUE THREAD

**Issue by austinpapp** [PowerlineApp/powerline-server#217]
i'm pretty sure the `/beta` endpoint is no longer necessary. let's remove its existence. 
https://github.com/PowerlineApp/powerline-server/blob/develop/backend/src/Civix/ApiBundle/Controller/SecureController.php#L475-L503

**Comment by austinpapp** [comment]
@jterps08 we have no need for this, correct?

**Comment by jterps08** [comment]
This is an e-mail sign-up link. You can remove it. We'll probably replace it with an industry standard widget like "hello bar" in the future for our landing page to capture e-mails. You can remove it
