### ISSUE TITLE
Add option to leader event throws vague exception

### ISSUE THREAD

**Issue by austinpapp** [PowerlineApp/powerline-server#229]
attempted to add options to leader event / poll id 188

```
{u'message': u'Civix\\CoreBundle\\Entity\\Poll\\Question object not found.', u'code': 404, u'errors': None}
```

this ended up happening because i forgot the poll id in the url. anyway this does highlight the vagueness of the error. this should respond with a properly formatted response not an exception. however im not sure if the exception is because the api is in dev mode.

**Comment by igaponov** [comment]
@austinpapp In prod you'll see only {"message": "Not Found", "code": 404}

**Comment by austinpapp** [comment]
we will worry about better error handling later. closing for now
