### ISSUE TITLE
ACL Security Enhancement for Assigning Group Manager Privileges

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-server#24]
We need the ability for a group owner/creator to assign any group member(s) to have group manager privileges, but the users must be group members first before they can get manager privileges assigned to them. 

Group managers can do everything group owners can (group management and content creation like polls, fundraisers, etc.)

however, they can *NOT* do the following: 

1. change group subscription level
2. assign other members as group managers. 

In general, the security setup in backend should be configured in such a way so that we can easily add/remove certain tools or settings to different profiles (group owner, group manager, group member). For example, in the future, we may want to allow all users to create fundraisers in their local town groups. Ideally, this should be as easy as changing a security setting.

Related: Issue #23 and Issue #22 
Related: As shown in mockup, this will be something the authorized user should be able to do very easily. 

![new assigning group manager within control component for web app extensions_preview](https://cloud.githubusercontent.com/assets/7582457/11853928/ca68e278-a40e-11e5-8bd4-4e1e04301323.jpg)

**Comment by shakaran** [comment]
@austinpapp @jterps08 this issue should be closed?
