### ISSUE TITLE
Confirm Elected Leader Registration/Assignment is working 

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-server#244]
_(To be completed after P1/P2 Bugs **and** Enhancements **and** after micropetition refactoring)_

The old FrontEndBundle allowed the following:
- Anyone could register as an elected leader at any level (local, state/province, national) through "Representatives" /representative/login
- Superuser needed to review registration and approve or reject. If approved, process below continues.
- If leader's name was found in database, the system linked the registration to the entry in the database. If leader's name was not found in database (e.g. local Mayor not in Cicero), the system linked that Mayor to all constituents in his town. 

Once a representative was registered and approved, he could log in and use available leader tools (polls/fundraisers/etc.) to reach out to his specific constituents. In other words, a State Senator could register and only _his_ constituents would receive the leader content he created. A mayor could register and only _her_ constituents would receive the leader content she provided. People that were not constituents of that State Senator or that Mayor would not receive the post and could not see the post. This functionality worked in v1.  It leveraged Cicero. If local official was not in Cicero, system linked local official to entire town where local official was based (Mayor to town, etc.).

Now, process needs to work as such:
- User registers on Powerline as normal.
- User submits special Representative form. 
- Superuser reviews and approves that user is actually the representative. 
- System links user to elected leader entity. / System assigns leader rights and privileges to interact with his specific constituents
- User has the ability to create leader content that is sent to all of his constituents. 
- Instead of posting to a particular group, the representative posts to an option "My Constituents" which are his _specific_ constituents (all the people that are linked to him through the Cicero DB). 

A user who is also a Mayor may have the following options to create content to: Town, State, Country, Save the Whales, Save the Trees, My Constituents. A user who is also a Senator may have the following options to create content to: Town, State, Country, Save the Trees, Labor Union X, My Constituents. A user who is not a representative may have the following options to create content to: Town, State, Country, Save the Trees, Save the Whales and may be able to create leader content to Save the Whales because he is a group manager for that group.

Leader content from a local official appears in the users town group. Leader content from a state/province official appears in the user's state/province group. Leader content from a national official appears in the user's country group. In each case, it's only visible for his specific constituents. 

To be discussed further, but we need this functionality.

**Comment by austinpapp** [comment]
i need to digest this a bit further but i agree we need to make sure we are at parity with v1. i'll updated as thoughts hit me. 

for now, we do in fact have leader content creation ability. however, the rep side of things we will need to confirm and explore a bit more. @igaponov i'll need your with reviewing that. 

I have some concerns with _superuser_. I hate the name but we will get beyond that for now :) anyway, i'm concerned that this user will be spending time / energy / resources investigating requests. this must be automated some how. exceptions and errors can be handled on an individual bases. we can create an "operator" panel to handle these things but with very limited action and abilities outside of simply approving a request.

**Comment by jterps08** [comment]
There's going to be many iterations ahead on this. I could imagine providing a photo ID as part of the process and that the user's name needed to match the entry in Cicero, etc. but for now, we don't need to get fancy and we can't afford to...

In the mean time, a superuser / God mode / system admin will be needed as step 1 to manually review requests. The review screen, like the current v1 solution, provides the registrant's info for review and verification. It's very hard to remove a human from this process without risking someone abusing the system. That said, the data provided through the registration process can help expedite / filter things a bit better.

**Comment by igaponov** [comment]
@jterps08 now process works as such:
* User registers on Powerline as Representative - we have 3 different entities now: User, Representative and Superuser (Group is used to be an entity too, but I've removed username/password and it's impossible now to register as a group)
* Superuser reviews and approves that user is actually the representative.
* System links user to elected leader entity (to a single local group). Not sure which rights you're talking about. Representative can't be a member, a manager or an owner of that group.
* Representative has the ability to create leader content that is sent to all of his constituents.
* Representative's constituents are linked to him through districts, local group or group sections (seems there is no direct connection in db).

**Comment by jterps08** [comment]
Thanks Igor...  this is tricky to explain, so let me try to break it down into details...

1. User registers on Powerline as Representative - we have 3 different entities now: User, Representative and Superuser (Group is used to be an entity too, but I've removed username/password and it's impossible now to register as a group) - PARTIALLY CORRECT
2. Superuser reviews and approves that user is actually the representative. - CORRECT
3. System links user to elected leader entity (to a single local group). Not sure which rights you're talking about. Representative can't be a member, a manager or an owner of that group. - DISCUSSED BELOW
4. Representative has the ability to create leader content that is sent to all of his constituents. - CORRECT
5. Representative's constituents are linked to him through districts, local group or group sections (seems there is no direct connection in db). - DISCUSSED BELOW

RE: Step 1 -- User JTest1 "Joe Smith" registers on Powerline. Then, we need JTest1 to submit a "Representative Registration" form for review and approval by superuser.... Mayor Joe Smith should have one unified account through JTest1 to interact with groups as a group member, as a group owner (e.g. Save the Whales), and as a Representative.... Joe Smith should *not* have one account to login to Powerline as group member/owner and a different account to login to Powerline as elected representative.

RE: Step 2 -- Joe Smith logged into Powerline in Step 1. He submitted his form for Representative approval as "Mayor" of Hoboken, New Jersey. In Step 2, the superuser is able to see his submitted form to review and approve "Mayor" rights for Joe Smith... 

RE: Step 3 -- "Mayor Joe Smith" may exist in our Cicero-powered database or may not (e.g. the Mayor of New York City is in our Cicero db, but not the Mayor of Hoboken)... In the case of local elected leaders (town-level), the leader does not need to be in our database in order to be 'linked' to the town group... So, when superuser approves JTest1 as "Mayor" for Hoboken (or City Councilman or Director of  Emergency Services, whatever local position), then the superuser is effectively giving JTest1 "elected leader" rights for the town. So we might have Mayor Joe Smith, Councilman John Cap, and Chief of Police Arthur Babbs who are *each* approved by superuser to have elected leader rights to the entire town (so, with their personal accounts, they can send polls/announcements/etc to entire town group).

For national-level elected leaders (President, Vice-President, US-Senators, US-Congressmen), it gets a little trickier:
Executive Officeholders (e.g. President/Vice-President) are linked to the entire nation/country. 
Legislative Officeholders (e.g. US Senators, US Congressmen) are linked to their districts, which should be entire states for US Senators (US Senator Cory Booker is all of NJ). For US Congressmen, it is parts of states (example: http://chrissmith.house.gov/district/ -- US Congressmen Chris Smith has only part of Middletown, NJ in his district)... So we have to use districts, not towns or entire states.

Same goes for State-level elected leaders (Governors, Lt. Governor, State Senators, State Assemblymen):
Executive Officeholders are linked to the entire state (E.g. Governor Chris Christie for all of New Jersey)
Legislative Officeholders (State Senators, State Assemblyman) are linked by their districts, which are parts of the state. For example, NJ State Senator Brian Stack is linked to the 33rd Legislative District in NJ - https://en.wikipedia.org/wiki/33rd_Legislative_District_(New_Jersey)

It's simple enough to understand when representative is linked by system to entire country group or entire state/province group or entire local group. Cicero should be able to tell us what State/Province that leader represents and we should be able to link the user to that state/province with leader content privileges... E.g. Cicero knows that Chris Christie is the governor of New Jersey, so we can assign User ChrisChristie1, with superuser review and approval, to the NJ group on Powerline. Even if leader is not in the Cicero database (for local level only), we should be able to understand that the leader is in the Hoboken group, superuser can review and assign approval, and user JTest1 (Mayor Joe Smith) has leader content privileges to Hoboken.... With local-level leaders who register and who are NOT in Cicero, the system currently in production stores the leaders provided (and reviewed/approved) information into database so that all local residents see that elected leader in their My Representatives screen. **AAA**

It's trickier when it comes to 'districts'... Cicero should know that Brian Stack is linked to the 33rd district. System should be able to review and approve user BStack44 for elected leader rights to the 33rd district. *When User BStack44 creates leader content, only citizens who are also in the 33rd district should see it appear in their feeds* **BBB**<--- This is the hard part!


AAA - Tricky part for local leader registration for leaders not in Cicero. This is already working in production!
BBB - Tricky part for linking approved leaders to districts AND linking citizens to districts. This is already working in production!

The challenge for BBB is that if I'm in 33rd district and you are in 32nd district and Brian Stack creates content, THEN only I should see it in my All/NJ feed - you should not be able to see the content Brian creates because he is not your elected leader. 

Of course push notification alerts, sorting, priority zone, etc. should work as usual for all leader content created by elected leaders...

I know this is hard to explain so feel free to ask questions.

**Comment by igaponov** [comment]
@jterps08 seems like the feature with districts/legislative really works in prod. But the problem is that User != Representative in backend.

1. If I understand right, we need to change our entities, so Representative will become just a characteristic of a User entity (User: Chris Christie => Representative: governor, New Jersey). This refactoring is not easy and fast, it'll probably take more time than our refactoring of leader content (allow user to edit group content from his account).
3.Question: should Senator Brian Stack be a manager in NJ group? I understood, that his content will be shown only for users from his district, but he should be able to create posts/polls etc in some group.

Now there is the next system of leader content on backend:
* User --[manages]--> Group --[has]--> Leader Content
* Representative --[has]-> Leader Content
To see leader content User can do:
* Open a page of a group -> to see group's content
* Open a page of a representative -> to see representative's content
User get notifications if:
* He is in a group (about group's leader content)
* He is in the same district with representative (about representative's content)

You want:
* User (can also be a representative) --[manages]--> Group --[has]--> Leader Content
* User (as a Representative) --[has]-> Leader Content
To see leader content User can do:
* Open a page of a group -> to see group's content (also created by a representative)
* Open a page of a user -> to see content for his constituents (posted to an option "My Constituents")
Notifications work in the right way now

**Comment by jterps08** [comment]
@igaponov let me think about what you've written and return my thoughts over the next few days... In the mean time, please work on the other issues... This (244) is complex so I want to make sure we're planning this correctly... 

My first thought is this - electeds do not need to 'manage' groups. They only need to be able to create leader content to send to their district (whether that's the 33rd legislative district, the town of Hoboken, or the State of New Jersey)... 

I will come back on other thoughts... Recategorizing this issue.

**Comment by igaponov** [comment]
@jterps08 but only managers can create leader content now, so representatives must be managers or we should add another role.

**Comment by jterps08** [comment]
That's fine @igaponov -- They can be managers, but the question is "managers of what?" ... A representative who is a manager of NJ Legislative District 33 is not a manager of 'NJ group' per se, only of district 33... This is where it's unclear to me how we should design it... 

Again, let's de-prioritize #244 until we can get some greater clarity on what we're trying to accomplish here...

Unlike a group owner/manager, an elected leader will *never* have to manage a group. They will only have to create leader content, which should only be delivered to their *specific* constituents... An elected leader will never have to manage group settings or anything like that. I don't know if we think of legislative districts as group subdivisions (e.g. 33rd legislative district is a type of sub-group of NJ group) or if they're there own independent groups but invisible to the end-user)... I just don't know yet, so let's come back to this later...

**Comment by jterps08** [comment]
@igaponov - Per your request: 

User registers on Powerline
User is connected to local, state/province, and country leaders per current process 
Backend leverages Cicero where needed, we try not to ping Cicero API too often because we have to pay the credits
User goes to My Representatives
User views linked leaders from Cicero. App may also display local leaders registered on Powerline that are linked to user’s town, but not in Cicero

User registers as elected leader (local/state/national)
User submits form with information as part of registration.
Superuser receives form and validates that the user is actually the elected leader who he claims to be (e.g. If user BarackObama registers and claims he’s the president, superuser needs to review information and validate he is the president).
See registration form fields below. Public constituent e-mail address. Non-Public e-mail address for Powerline staff only. Public constituent phone number. Non-public phone number for Powerline staff only. 
When superuser approves, the representative’s profile is updated with provided Public E-mail and Public Phone number… Other fields come from Cicero/Sunlight still. 

Approved as a representative, the user logins in to Powerline
User can create new leader content for any groups he is an authorized leader for.
User now has ability to create new leader content for “My Constituents” 
Sending leader content to “My Constituents” will be delivered to all of his specific constituents (e.g. If Mayor or Councilman or Local, all citizens in town. If Governor, US Senator, all citizens in State… If Congressman or Assemblyman or State Senator, all citizens in district… If President or Vice President, all citizens in country)
The content is displayed in the user’s Town, State/Province, or Country group according to whether or not it came from a Local, State/Province, or National Elected leader. Congressman appears in Country group. Assemblyman or State Senator appears in State group.

**Comment by jterps08** [comment]
Closing this. Will retest in Staging.
