### ISSUE TITLE
Confirm Push Notifications Work Correctly

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-server#254]
The following events should result in push notifications:

- Leader sends poll, petition, discussion, fundraiser, event, or announcement (all group members notified)
- User post is boosted automatically by system in a group
- User post is manually boosted by group leader.
- User A receives follow request from User B
- User A receives a notification when a user he follows, User B, creates a new post in the same group as him
- User is invited to join group.
- Group Permissions have been changed for a Group
- User is @mentioned by another user
- User has subscribed to notifications to a post (notified for new comments)
- Author is subscribed (by default) to his own post (notified for new comments and new upvote/downvotes)

**Comment by igaponov** [comment]
@jterps08 
* push for polls (petition, discussion etc) is sending only on boost.
* what is the difference between manual and auto boosting of a post?
* there is a push only when user is mentioned in comments.

**Comment by jterps08** [comment]
Interesting. I'm not sure why this changed... 

So, each of the scenarios I listed above should have push notification alerts. This is how it is working in production right now and push notifications are critical to the app so we need to have all of these push notification alerts working. In each scenario, we should still be honoring the Notifications Content Adjustments work we've done in the past: https://drive.google.com/file/d/0B2Loy21ehREySWgwUmJtZDRaN3M/view

A push notification alert should be sent to all group members for any new published leader content: polls, petitions, discussions, fundraisers/crowdfunders, events, and announcements.

A post (micropetition) is automatically boosted by the system based on the boosting level (quorum level) of that group. Eg. If the quorum level is 10% and the membership size is 90 people, then the boosting level is 9 upvotes. At first, only the author's followers in that group receive a push notification alert. Once the post reaches 9 upvotes, a push notification alert is sent out to all group members for the post, and it is treated as priority zone content until answered (upvote/downvote/ignore). The quorum/boosting level can be adjusted by the group leaders (see prod setting below).
![image](https://cloud.githubusercontent.com/assets/7582457/17837705/0b7afc5a-6788-11e6-99e7-2f171a68c1cf.png)

An authorized group leader should also be able to manually boost any post in the group. The prod capability for this is below. A manually boosted post results in a push notification alert being sent out to all group members for the post, and it is treated as priority zone content until answered (upvote/downvote/ignore). See prod capability below.
![image](https://cloud.githubusercontent.com/assets/7582457/17837681/22929e26-6787-11e6-877a-ebb2bb73c9f3.png)

Yes, a push notification alert should be generated for when a user is @mentioned, but also for the other scenarios above listed in original comment. This is current production behavior. The only exception to production behavior is these two, which are new: 

1. User has subscribed to notifications to a post (notified for new comments)
2. Author is subscribed (by default) to his own post (notified for new comments and new upvote/downvotes)

Each of these should have been addressed previously here: https://github.com/PowerlineApp/powerline-server/issues/40 and
https://github.com/PowerlineApp/powerline-server/issues/57

I do not know what was impacted by the Event Listener work: https://github.com/PowerlineApp/powerline-server/issues/85

**Comment by igaponov** [comment]
@jterps08 
1. A push notification alert is sending to all group members for any new PUBLISHED leader content now (I thought "Leader sends poll, petition etc" means "Leader creates it"), so it's done.
2. Should author's followers receive push alert twice, first time when post is created and second time when it's boosted? Also, do we need to send push about user petition? When I split micropetitions, I copied this functional.
3. User can be mentioned in comments, posts and user petitions (we added mentions for posts and petitions [here](https://github.com/PowerlineApp/powerline-mobile/issues/145)), but only for comments he will receive a push. Do we need to add it for posts and petitions?

**Comment by jterps08** [comment]
1 - Great. Yes, definitely on publish only :-) for leader content.
2 - Leaders followers should receive push notification twice (first for followed user's post, second for boosted post)... Also, Yes for user petitions too. :+1: 
3 - Nope. He should only receive a push for comments for right now. We may add it for posts in the future. So we're also good :100:

**Comment by jterps08** [comment]
@petervojtek - I am ready to proceed with testing notifications when provided with next testing build.

**Comment by jterps08** [comment]
closing. All notifications are working at least for Android v4.4. Will continue to track this item using mobile repo #226.
