### ISSUE TITLE
admin-dev not rendering

### ISSUE THREAD

**Issue by austinpapp** [PowerlineApp/powerline-server#281]
@igaponov when i go to the dev server, i'm getting
```
No matching accepted Response format could be determined
406 Not Acceptable - NotAcceptableHttpException
```
We need to figure out why the frontend is not rendering.

**Comment by jterps08** [comment]
What is our status on this?

**Comment by igaponov** [comment]
@jterps08 there is some problem with ip, admin-dev points to wrong ip address. @austinpapp should check it.

**Comment by jterps08** [comment]
I'm still unclear about our status with this @austinpapp ?
