### ISSUE TITLE
Friend Finder Endpoint

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-server#34]
i1: Add endpoint to return whether a provided hashed e-mail address is linked to an existing Powerline account. This will help us enable a front-end capability to find friends to follow based on e-mail addresses in the user's address book without sacrificing user privacy.

Out of scope: In the future (i2), we will iterate to provide and compare hashed phone numbers.

Out of scope: In the future (i3), we will iterate to make recommendations based on friends of friends (acquaintances).

**Comment by austinpapp** [comment]
@igaponov can you provide me with a sample request?

**Comment by igaponov** [comment]
@austinpapp sure!
Request:
GET localhost:8080/api/search/friends?limit=10&page=1&emails[]=2d803a5bd01cd1981d5034493078a9d22aa22da6&emails[]=5420dcca095bf1b4af7641ead746253b0875899c&emails[]=xxx

Return:
200 OK
[{"full_name":"user2 user2","id":2,"username":"user2","first_name":"user2","last_name":"user2","avatar_file_name":"http:\/\/localhost:8080\/bundles\/civixfront\/img\/default_user.png","birth":"10\/01\/1980","country":"US"}, ...]

**Comment by austinpapp** [comment]
resolved by #32
