### ISSUE TITLE
Confirm Daily Payouts for Group Accounts

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-server#388]
For groups that have setup their bank account information, they should get paid out on a daily basis with no delay. Can you confirm we have this setup properly from a backend standpoint when setting up customer / bank account for a group entity? I think the default from a Stripe perspective is the minimal value allowed for interval (which should be daily and 0 for delay)... 

https://stripe.com/docs/connect/bank-transfers#payout-information

**Comment by igaponov** [comment]
@jterps08 no, I can't find any mention about `transfer_schedule` on backend

**Comment by jterps08** [comment]
Okay - let's leave this open for now... I think the default on Stripe's side means that, as long as we setup the account correctly, that the transfer will happen daily anyway.. We'll have to come back and confirm after we're setup. Assigning to me for verification.
