### ISSUE TITLE
Production Deployment Readiness

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-server#446]
We need to be able to deploy dev to Production and leverage Staging if needed. Currently dev is working great. We need to ensure we can deploy to staging and production as needed.

**Comment by igaponov** [comment]
@jterps08 I can't change deployment configs for prod, only @austinpapp  can do it. And I still don't have an access to staging.

**Comment by austinpapp** [comment]
working on some details on staging/production now.

**Comment by igaponov** [comment]
@jterps08 should we close this?

**Comment by jterps08** [comment]
Yes. Definitely :-)
