### ISSUE TITLE
Basic User Post & User-Petition Data Analytics

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-server#464]
The short-term objective is to be able to report the following:
Of the 1000 people who upvoted this post (or signed this petition), 25% are Cory Booker's constituents. 
Of the 1000 people who upvoted this post (or signed this petition), 25% live in Hoboken, New Jersey. 

The long-term objective is to be able to report the following:
Of the 1000 people who upvoted this post (or signed this petition), 25% are Cory Booker's constituents. Of those, 50% are Democrats. Of those, 80% are under the age of 34. 

This is critical. 

Eventually, it would be good to drill-down this data. However, for now, I will simply be satisfied with counts descending from largest to smallest.

To achieve this, I think we need to track the user's linked elected leaders in a separate table. It probably makes sense to hav ea different table that links each user to their town, state, and country groups so that we can do reports on those as well. 

User A Leader 1 Leader 2 Leader 3 Leader 4 etc
User B Leader 1 Leader 2 Leader 3 Leader 4 etc
User C Leader 3 Leader 7 Leader 8 Leader 1 etc

Another way to think of this is this way: Instead of thinking of User A signing the post/petition, think instead that each of User A's linked elected leaders are signing the post/petition. Then, we aggregate the signatures to figure out who has been linked to them the most. 

As far as I'm concerned, this can be a totally different application that connects into a cloned database... but we will want an endpoint available, for authorized users, to access the read-only data. We will want the mobile app to eventually be able to display. 

Let's talk about this in a dedicated channel on Slack.

**Comment by igaponov** [comment]
@jterps08 now for membership roster report we use a table `user_representative_report` with columns `president`, `vice_president`, `senator1`, `senator2`, `congressman`.
We don't need a cloned db, but a table (or separate special db) for analytics, where we can store denormalized data for fast queries. The problem is that you want reports with variable number of columns (for example groups have different number of fields) and we can't use relational db for it.

**Comment by jterps08** [comment]
Thanks for this commentary @igaponov... Let me create a channel so we can get this in Slack...
