### ISSUE TITLE
missing symfony files

### ISSUE THREAD

**Issue by austinpapp** [PowerlineApp/powerline-server#473]
looks like a bunch of files are missing since commit ec179ee4b2856e228bb10da6a0b0caa4e732f966
did you mean to delete things like `app/console`?

https://github.com/PowerlineApp/powerline-server/commit/ec179ee4b2856e228bb10da6a0b0caa4e732f966#diff-86cc74061ce8572d3a9e764d501ab34d

**Comment by igormukhingmailcom** [comment]
At symfony3 this file placed at different location:
https://github.com/PowerlineApp/powerline-server/blob/develop/backend/bin/console

**Comment by austinpapp** [comment]
yea... just sorted that out. thanks for the update @igormukhingmailcom . good to hear from you.
