### ISSUE TITLE
Notifications Content Adjustments (Titles/Messages/Avatars)

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-server#51]
Updating non-FrontBundle Notifications Titles, Messages, and Avatars according to the detailed guidance in a provided e-mail to @igaponov

**Comment by jterps08** [comment]
Details for future reference: https://drive.google.com/open?id=0B2Loy21ehREycm1jYjVrV0dSZ2s

**Comment by jterps08** [comment]
Details for future reference: https://drive.google.com/open?id=0B2Loy21ehREySWgwUmJtZDRaN3M

**Comment by jterps08** [comment]
Did we ever make these changes @igaponov? Was this part of PR #48?

**Comment by igaponov** [comment]
@jterps08 yes, we did in #48. Just the same changes that is in your pdf file.

**Comment by jterps08** [comment]
@igaponov How about the "Out of Scope" section in the PDF. Did we ever do that work?

@austinpapp I think we were never able to make those notification changes because of Angel's work, right?

If we still have to do that work under Out of Scope, I'll create a new issue for it.

**Comment by igaponov** [comment]
@jterps08 we did "Out of Scope" too, I see these changes in the code.

**Comment by jterps08** [comment]
Thanks, @igaponov - I wasn't sure what we had done there :-)
