### ISSUE TITLE
Temporary ALL Notification Muting

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-server#54]
The backend needs to support a "flag" that allow users to mute all notification alerts to their device for pre-defined time durations: 1 hr, 2 hr, 4 hr, 8 hr, 12hr, 24 hr, 3 days. This will result in no push notification *sound* or *LED* for notifications delivered to the user's device. It will also result in *notification replacement* (see below) for all notifications during the period of muting. The app will continue to update with fresh content but there will be no sound, vibration, or LED message on the mobile device.

App turns muting flag on in the backend for the user... notification is about to be produced, if muting flag is on, then is_mute would be passed with notification to turn off sound and LED for notifications and ... When muting flag is off, the default/current settings return to normal.

Background Note: Currently, anytime a notification is delivered to the mobile device, it is delivered as a separate, independent notification in the OS drawer. So, if 7 notifications are delivered, 7 notifications appear in the OS drawer. We can change this so that if 7 notifications are delivered, only the *most recent* appears in the OS drawer. [Notification stacking](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#stacking) is available in the current plugin, but we do not want to activate stacking - but do reference the first couple lines of the documentation in that section:

> By default when using this plugin on Android each notification that your app receives will replace the previous notification in the shade.

>If you want to see multiple notifications in the shade you will need to provide a notification ID as part of the push data sent to the app. For instance if you send:

>{
>    "registration_ids": ["my device id"],
>    "data": {
>        "title": "Test Push",
>        "message": "Push number 1"
>    }
>}

During "muting" period, multiple notifications will be disabled. Every new notification will replace the previous notification in the shade. When muting period is over, we will return to multiple notifications in the shade.

**Comment by austinpapp** [comment]
was this handled on the frontend?

**Comment by jterps08** [comment]
No. I am closing and will re-open at the appropriate time. It is very low priority relative to our roadmap items.
