### ISSUE TITLE
Avatar resizing error when avatar is not an image

### ISSUE THREAD

**Issue by igaponov** [PowerlineApp/powerline-server#560]
app.CRITICAL: Avatar resizing error. {"exception":"[object] (Intervention\\Image\\Exception\\NotReadableException(code: 0): Unable to read image from file (/tmp/temp_file_******). at vendor/intervention/image/src/Intervention/Image/Gd/Decoder.php:20)"}

**Comment by igaponov** [comment]
@jterps08 not sure how you can test it. The problem was with representatives, when representative's avatar url redirected to an html page and image processor wasn't be able to create an image from an html file. We validate user's input, so a user can upload only files with allowed extensions, but we trust cicero and don't validate its input. After this change if an uploaded file from cicero is invalid, default avatar will be set.

**Comment by jterps08** [comment]
No worries. I trust you. Thanks @igaponov . Please close it if you think it makes sense to close.
