### ISSUE TITLE
Saved Items Endpoint

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-server#59]
Basically we need an endpoint that stores the saved items for the user (storage/removal). The backend does not need to have a limit in place. We will control the 10-item limit from the frontend...

The endpoint should support adding an item, removing an item, and listing all items (w/ paging). The system should store the item-type, item ID, and userID so that the mobile app can retrieve and display the appropriate saved items to the user. I am suggesting item-type because I don't know if poll IDs are unique from post(micropetition) IDs or discussion IDs etc - if they're all unique, then this field is not necessary.

Example: User A can tap a "star" icon in the front-end to save a post via the API endpoint. Un-starring an item remove the post from the saved items list. User A has 3 saved posts (micropetitions), 2 saved discussions, 2 saved events. The mobile app displays the 7 items. The user can add/remove items from the list at any time.

For additional perspective, check out the front-end design explanation(out of scope) below:
The user will be able to tap a ion-star icon on any post. This icon will be located on the newsfeed quick action bar. Tapping the star will create toast that says “Saved to Favorites.” If the star is untapped, the toast will appear saying “Removed from Favorites.” The default fill of the icon will be an inactive-gray. Upon being tapped, it will turn Yellow. The user should only be able to have 10 favorites concurrently. The Menu will have a new item added that is labeled “Favorites”. Upon tapping this, a screen is displayed that shows all of the Favorites in a newsfeed-style listing. The newsfeed will NOT have the group selector component (e..g all button, etc.) or the Feed Selector component (three-person icon, etc.)

**Comment by austinpapp** [comment]
closing this but will be expanding this here https://github.com/PowerlineApp/powerline-mobile/issues/37#issuecomment-230341219 . this also defines what is needed.
