### ISSUE TITLE
Error when generate entity in develop branch

### ISSUE THREAD

**Issue by habibillah** [PowerlineApp/powerline-server#81]
`$ php app/console doctrine:generate:entities Civix`
>  [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]
> The service "imgix.url_builder" has a dependency on a non-existent parameter "imgix.domain".  
                                                                                                
The quick fix is removing related arguments in `src/Civix/CoreBundle/Resources/config/services.xml` but it will not fix the real issue. I assume some one has missed to commit his/her modified `service.xml` file.

**Comment by igaponov** [comment]
https://github.com/PowerlineApp/powerline-server/blob/develop/backend/app/config/parameters.default.yml#L61

**Comment by austinpapp** [comment]
@habibillah as @igaponov has pointed out, that parameter is available in latest develop. have you rebased from develop?
