### ISSUE TITLE
PHPUnit testing enviroment broken

### ISSUE THREAD

**Issue by shakaran** [PowerlineApp/powerline-server#94]
When you try to run phpunit in test enviroment, the WebTestCase class is missing in GroupManagerTest.php This reference to @igaponov comment in https://github.com/PowerlineApp/powerline-server/pull/84#issuecomment-197283905

Assigning to @habibillah 

	vagrant@vagrant-ubuntu-trusty-64:/vagrant/backend$ phpunit -c app
	PHP Fatal error:  Class 'Civix\CoreBundle\Tests\Service\Group\WebTestCase' not found in /vagrant/backend/src/Civix/CoreBundle/Tests/Service/Group/GroupManagerTest.php on line 9
	PHP Stack trace:
	PHP   1. {main}() /usr/bin/phpunit:0
	PHP   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:46
	PHP   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:129
	PHP   4. PHPUnit_TextUI_Command->handleArguments() /usr/share/php/PHPUnit/TextUI/Command.php:138
	PHP   5. PHPUnit_Util_Configuration->getTestSuiteConfiguration() /usr/share/php/PHPUnit/TextUI/Command.php:657
	PHP   6. PHPUnit_Util_Configuration->getTestSuite() /usr/share/php/PHPUnit/Util/Configuration.php:789
	PHP   7. PHPUnit_Framework_TestSuite->addTestFiles() /usr/share/php/PHPUnit/Util/Configuration.php:873
	PHP   8. PHPUnit_Framework_TestSuite->addTestFile() /vagrant/backend/vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php:416
	PHP   9. PHPUnit_Util_Fileloader::checkAndLoad() /vagrant/backend/vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php:355
	PHP  10. PHPUnit_Util_Fileloader::load() /usr/share/php/PHPUnit/Util/Fileloader.php:76
	PHP  11. include_once() /usr/share/php/PHPUnit/Util/Fileloader.php:92

**Comment by habibillah** [comment]
Scroll down to this [comment](https://github.com/PowerlineApp/powerline-server/pull/84#issuecomment-198162707). will fix after that [PR](https://github.com/PowerlineApp/powerline-server/pull/82) merged.

The history of this issue come from [this one](https://github.com/PowerlineApp/powerline-server/pull/82#issue-140620890) if you care.
